apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
  namespace: singhsabha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: www
          image: ghcr.io/singh-sabha/www:v3.0.1 # {"$imagepolicy": "flux-system:www"}
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: singhsabha-secret
                  key: DATABASE_URL
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: singhsabha-secret
                  key: RESEND_API_KEY
            - name: YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: singhsabha-secret
                  key: YOUTUBE_API_KEY
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: singhsabha-secret
                  key: STRIPE_SECRET_KEY
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: singhsabha-secret
                  key: GOOGLE_API_KEY
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: singhsabha-secret
                  key: SECRET_KEY_BASE
            - name: BUCKET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: singhsabha-secret
                  key: BUCKET_ACCESS_KEY
            - name: BUCKET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: singhsabha-secret
                  key: BUCKET_SECRET_KEY
            - name: BUCKET_HOST
              valueFrom:
                secretKeyRef:
                  name: singhsabha-secret
                  key: BUCKET_HOST
            - name: PHX_HOST
              value: "singhsabha.net"
            - name: PHX_SERVER
              value: "true"
            - name: RELEASE_COOKIE
              valueFrom:
                secretKeyRef:
                  name: singhsabha-secret
                  key: ERLANG_COOKIE
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
