apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: singhsabha-secret
  namespace: singhsabha
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: singhsabha-secret
  dataFrom:
    - extract:
        key: singhsabha
