apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: www
  namespace: flux-system
spec:
  image: ghcr.io/singh-sabha/www
  interval: 5m
  secretRef:
    name: ghcr-secret
