resources:
  - deployment.yaml
  - external-secret.yaml
  - ghcr-external-secret.yaml
  - ingress.yaml
  - service.yaml
  - image-repository.yaml
  - image-policy.yaml
  - image-update-automation.yaml
