apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: apps-singhsabha
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: postgres-secret
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: apps/singhsabha-postgres
        property: POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: apps/singhsabha-postgres
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: apps/singhsabha-postgres
        property: POSTGRES_PASSWORD
