apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: singhsabha-postgres
  namespace: singhsabha
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: singhsabha-postgres
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: singhsabha-postgres
        property: POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: singhsabha-postgres
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: singhsabha-postgres
        property: POSTGRES_PASSWORD
